### ISSUE TITLE
Review design with respect to basic UX principles

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#41]

**Comment by nickcoluccio** [comment]
**Peformance load**

- **Hardware:** We designed the hardware to decrease both cognitive and kinematic load. We reduced kinematic load by using easy to push buttons and by making the more frequently used buttons bigger and closer to the screen, while settings buttons are in their own separate area. We also reduced cognitive load by designing stickers that easily explain the buttons given purpose. If you want to quickly get the machine working we also pre installed settings and timings so that the user can begin immediately if they don't want to bother playing around with the settings. 

- **Software:** We reduced kinematic load by placing the text boxes where you select your desired times or your tasks in the middle of the screen near the start button so you don't have to move the mouse far. We reduced cognitive load by placing the start timer buttons near the boxes where you input the times. We also placed all of the inputs for the timers in a logical order, work time then break time. For the task mode, we put the box where you input the task on the left and the list of all tasks on the right, since westerners go from left to right. 

**Flexibility - usability tradeoff**

- While our idea was mostly focused on the accountability of the LEDs to make the person continue working, we wanted to make the product flexible so that as many people as possible would be able to study/ be productive in a way that suits them. We decided that we would have three different modes to try to accommodate as many study styles as possible. The first one is a the standard pomodoro method with a normal working and break time. The second one is where you input a given set of tasks for the day and mark them complete on your own time. The third one you set yourself a given amount of break time for the whole day. You can set these functions on either the hardware or software, but to keep the hardware more simple we allowed only timing changed of 5 minutes but you can get more technical on the software for those who enjoy customizability. 

**Visibility**

- On the physical device we will have a display that will show what mode they are editing and if they are currently in a mode which mode they are in. The software you are not allowed to leave the given page so you know what mode you are in. We didn't make it too complicated the use should be able to figure out who to cycle through the modes and input their preferences with relative ease and just scrolling through the options. The settings buttons are also placed off to the side and are smaller so that the user sees them but knows they are not as important. 

**Feedback**

- When updating the settings it will be visible on the hardware display that you are updating the desired settings for that mode as the times/ tasks will change. When in an actual mode, there will be like a status pane in the bottom portion of the display that will let the user know their current mode, whether its break time or not for pomodoro mode, how many tasks left for task mode and other useful information. If pressing the play/pause button or the off for day button we can also play a sound on the buzzer to let the user know that the button was pushed or after all the settings have been completed. 

**Constraint**

- We don't allow the user to access the turning on or off of LEDs as this would defeat the purpose of the whole design and the idea of them having to be productive to be rewarded to have the LEDs turn on to make the tree look nice. We only allow the user to input their times and they are responsible for being honest with themselves and getting the work done to get the proper visual reward. The user has their mistakes minimized because of the way we organized the buttons and the software interface to make it very clear and easy to how the convention works. When inputting the settings, they have to move to the next "level" of settings selection by once again pressing the settings button which is similar to how those digital watches are programmed. Then we have a basic up down button which will increase or decrease the time as they want. 

**Forgiveness**

- Our design also helps minimize error through forgiveness since we have an exit button on the software which will allow the user to exit button on software or the done for day on the hardware to cancel the given mode if they input an incorrect time when initally setting up. If they are midway through  one task and they decide that they do not want to continue with the last pomodoro or they initially inputted too many tasks, they merely have to go back into settings to change it and the LEDs and display will update accordingly. 

**Affordance**

- On our software interface, we will have little pictures for each mode that will afford the usage of that mode if the user forgets. For the pomodoro mode we will have a clock, indicative of its timed nature. For the task mode we will have a check, which is indicative of a task list that you check when completed. For the break mode we will have a coffee mug which is indiciative of taking a break. These images will help to negatively afford improper use. On the hardware display since the screen is quite small, we will make the mode be represented by the first letter of the mode. The design as a whole is afforded well as most people understand and want  a tree to flower and blossom, so the goal is to be productive to have the tree flower up with the LEDS. 

**Confirmation**

- Before the user can start any task after changing the settings they are prompted with an "OK?" to confirm these settings or else they will have to re input the settings if no action taken.
