### ISSUE TITLE
Review wireframes WRT UX basics

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#48]

**Comment by tgao1337** [comment]
We talked to Professor Fund about this, Please see diagram and will talk about this tonight.

**Comment by nickcoluccio** [comment]
@ffund , We re designed our buttons as follows, we have a start/end day button. We also have play/ pause  button we discussed for the pomodoro and budget modes, but for the task mode we also need a way to signal task completed and thought we could use this button as well instead of creating another separate button for the task completed. Is this too confusing? Also we moved all of our settings editing buttons away further away from the more used buttons.
![w](https://user-images.githubusercontent.com/72901664/163298397-f0b5cbdd-8a05-485e-98d0-51f2b3b44839.JPG)

**Comment by shahzebnaseer** [comment]
Here's the updated wireframe: [Flexible Pomodoro Tree Wireframe V2.pdf](https://github.com/tgao1337/flexible-pomodoro-tree/files/8485714/Flexible.Pomodoro.Tree.Wireframe.V2.pdf)

**Comment by shahzebnaseer** [comment]
Final wireframe: [Flexible Pomodoro Tree Wireframe - Final.pdf](https://github.com/tgao1337/flexible-pomodoro-tree/files/8556235/Flexible.Pomodoro.Tree.Wireframe.-.Final.pdf)
We will be using five buttons:
- Settings (to select the mode and change mode-specific settings)
- Up (to count up / scroll up)
- Down (to count down / scroll down)
- Play-Pause-Check (to pause or resume and also to mark tasks as done for Task mode)
- Start/End of the Day (keeps LED on at End of the Day, press again to reset)
