### ISSUE TITLE
Setup Flask - User Interface

### ISSUE THREAD

**Issue by shahzebnaseer** [tgao1337/flexible-pomodoro-tree#58]
- [x] Create pages using Bootstrap
- [x] Setup Flask using those pages

**Comment by ffund** [comment]
1. Update the issue with a comment showing what happens when you try to run this. Does it run, but you can't access the web interface? Does it not run at all? Include a screenshot.
2. Note that the `join` calls will not return until those threads end - so, never! If there's something that should run, it should go before the calls to `join`.

**Comment by tgao1337** [comment]
1. Originally the browser UI did not run (the server would not start  up) and the application ran perfectly when we had it as separate files. 
2. We moved it to a single file as you suggested, and put the flask code after the start of the threads but before the join as seen here: https://github.com/tgao1337/flexible-pomodoro-tree/blob/main/pomodorotree_v2.py#L554

https://user-images.githubusercontent.com/12534586/167075036-703d5ae8-f95e-429c-b328-e464eb4cde21.mov


Now our application layer and browser interface seems fine but the display is not updating smoothly as it used to. We can access the browser UI and see the timer and other parts working fine when we press the buttons, but the display looks really glitchy and does not update smoothly. Please see attached video.

**Comment by ffund** [comment]
Here are a few suggestions:

* In `updateDisplay()`, you can change all the `if` statements except the first to `elif`, so that it will only write to the display once on each iteration of the outer `while` loop. Then, at the end of the `while` loop (inside the loop, but after writing to the display), you can add a short `sleep` so that you know the display should be stable for at least that long. 
* You can change to `debug=False` here to use less CPU: https://github.com/tgao1337/flexible-pomodoro-tree/blob/34b4c628a0f291f60282a4baa6998418224fa2d2/pomodorotree_v2.py#L577
